
repos:
  - repo: local
    hooks:
      - id: default
        name: pre-commit check
        description: Run placeholder pre-commit check as a test
        language: system
        entry: echo
        args:
          - 'Running pre-commit check...'
        files: ''
      - id: test
        name: pytest
        description: Run tests with pytest
        language: system
        entry: pytest
        types:
          - python
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
