# GitHub Action
# description: Publish newly-versioned packages to NPM
# author: Matt Norris <matnorri@cisco.com>
# references:
#   - https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

name: Publish Packages
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Version Packages"]
    branches:
      - main
      - version-packages
    types: [completed]
jobs:
  publish-packages:
    runs-on: ubuntu-latest

    # Publish the packages if the "Version Packages" workfow succeeded.
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      #
      # Set up
      #

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GVE_APP_SUPPORT_ACCESS_TOKEN || github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      # Configure git so Lerna can function properly.
      - name: Configure git for Lerna
        run: |
          git config user.name "GVE App Support"
          git config user.email "<>"

      - name: Install
        run: npm run lerna:ci

      #
      # Publish
      #

      # Use CI system automation.
      # https://github.com/lerna/lerna/tree/main/commands/publish#--no-verify-access
      - name: Publish packages to NPM 📦
        run: npm run lerna:publish:auto -- --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
