# GitHub Action
# description: Versions packages merged into main
# author: Matt Norris <matnorri@cisco.com>
# references:
#    - [Trigger when PR is merged](https://stackoverflow.com/a/67833464/154065)

name: Version Packages
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - gh-actions
    types: [closed]
jobs:
  version-packages:
    # Was the PR merged?
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/fermium"
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GVE_APP_SUPPORT_ACCESS_TOKEN }}"
      # Configure git credentials for Lerna.
      - uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: "${{ secrets.GVE_APP_SUPPORT_ACCESS_TOKEN }}"

      - run: npm run lerna:ci
      - run: npm run lerna:version -- --yes

      - name: Push tags to the repository
        if: |
          contains(github.ref, 'main') ||
          contains(github.ref, 'gh-actions')
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GVE_APP_SUPPORT_ACCESS_TOKEN }}
          branch: main
          tags: True
