# GitHub Action
# description: Versions packages merged into main
# author: Matt Norris <matnorri@cisco.com>
# references:
#    - [Trigger when PR is merged](https://stackoverflow.com/a/67833464/154065)

name: Version Packages
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - gh-actions
    types: [closed]
jobs:
  print-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print the triggering branch
        run: |
          echo "PR triggered by this branch: ${{ github.event.pull_request.head.ref }}"
          echo "github.ref: ${{ github.ref }}"

  version-packages:
    runs-on: ubuntu-latest

    # Version the packages if the PR was merged.
    if: |
      github.event.pull_request.merged &&
      contains(github.ref, 'main')
    steps:
      #
      # Set up
      #

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GVE_APP_SUPPORT_ACCESS_TOKEN || github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      # Configure git so Lerna can function properly.
      - name: Configure git for Lerna
        run: |
          git config user.name "GVE App Support"
          git config user.email "<>"

      - name: Install
        run: npm run lerna:ci

      #
      # Version
      #

      - name: Version the packages
        run: npm run lerna:version -- --yes

      - name: Push tags to the repository
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GVE_APP_SUPPORT_ACCESS_TOKEN }}
          branch: main
          tags: True

      #
      # Publish
      #

      # Use CI system automation.
      # https://github.com/lerna/lerna/tree/main/commands/publish#--no-verify-access
      - name: Publish packages to NPM 📦
        if: success()
        run: npm run lerna:publish:auto -- --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
