# GitHub Action
# description: Versions packages merged into main
# author: Matt Norris <matnorri@cisco.com>
# references:
#    - [Trigger when PR is merged](https://stackoverflow.com/a/67833464/154065)

name: Version Packages
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - gh-actions
    types: [closed]
jobs:
  print-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print the triggering branch
        run: |
          echo "PR triggered by this branch: ${{ github.event.pull_request.head.ref }}"
      - name: Print if this is an automated PR
        if: contains(github.event.pull_request.labels.*.name, 'automated')
        run: |
          echo "PR has this label: automated"

  version-packages:
    # Version the packages if the PR merged was not created by this workflow.
    # Otherwise, this job will create PRs in an endless loop.
    if: github.event.pull_request.merged && !contains(github.event.pull_request.labels.*.name, 'automated')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GVE_APP_SUPPORT_ACCESS_TOKEN || github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      # Configure git so Lerna can function properly.
      - name: Configure git for Lerna
        run: |
          git config user.name "GVE App Support"
          git config user.email "<>"

      - name: Install
        run: npm run lerna:ci

      - name: Version the packages
        run: npx lerna version --conventional-commits --yes
